import type { ExtractionResult, UserConfig } from "./types"
import dump from "./demo/proposals.json"

// Dev-only: no BYOK key set, so the landing shows the "connect your own" nudge
// and the config view shows the connect form. Flip gemini_api_key to
// { set: true, last4: "9abc" } to preview the connected state.
export const MOCK_CONFIG: UserConfig = { byok: { gemini_api_key: null } }

// Real pipeline output: the full 54-proposal run against the demo bundle
// (James Lee, 4 notes). Generated by backend/dump_demo_proposals.py — the
// actual extraction result, not a hand-curated subset.
export const MOCK_RESULT: ExtractionResult = {
  ...(dump as unknown as ExtractionResult),
  stats: { duration_ms: 24100, total_cost_usd: 0.041 },
}
