import type { ExtractionResult, UsageData, UserConfig } from "./types"
import dump from "./demo/proposals.json"

// Dev-only: a few runs so the Account → Usage panel has data to render.
export const MOCK_USAGE: UsageData = {
  summary: { runs: 3, total_cost_usd: 0.1271, input_tokens: 184200, output_tokens: 21400 },
  runs: [
    { id: "use_a1", ts: "2026-06-18T15:12:00Z", model: "gemini-3.5-flash", input_tokens: 61400, output_tokens: 7200, cost_usd: 0.0418, duration_ms: 24100, doc_count: 4, status: "completed" },
    { id: "use_a2", ts: "2026-06-18T11:48:00Z", model: "gemini-3.5-flash", input_tokens: 58900, output_tokens: 6900, cost_usd: 0.0401, duration_ms: 22800, doc_count: 4, status: "completed" },
    { id: "use_a3", ts: "2026-06-17T16:30:00Z", model: "gemini-3.5-flash", input_tokens: 63900, output_tokens: 7300, cost_usd: 0.0452, duration_ms: 25600, doc_count: 3, status: "completed" },
  ],
}

// Dev-only: a connected key so landing/settings previews show the configured
// state. Use ?preview=connect to see the Connect Gemini gate instead.
export const MOCK_CONFIG: UserConfig = { byok: { gemini_api_key: { set: true, last4: "9abc" } } }

// Real pipeline output: the full 54-proposal run against the demo bundle
// (James Lee, 4 notes). Generated by backend/dump_demo_proposals.py — the
// actual extraction result, not a hand-curated subset.
export const MOCK_RESULT: ExtractionResult = {
  ...(dump as unknown as ExtractionResult),
  stats: { duration_ms: 24100, total_cost_usd: 0.041 },
}
